markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "KISS"
markdown: rdiscount

author: "yorks"
atom-baseurl: "http://kiss.qwer1234.info"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://yangyou.lofter.com/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

